CYPHER 25
CREATE CONSTRAINT product_sku IF NOT EXISTS
FOR (n:Product) REQUIRE n.sku IS UNIQUE;

CYPHER 25
CREATE CONSTRAINT part_part_number IF NOT EXISTS
FOR (n:Part) REQUIRE n.part_number IS UNIQUE;

CYPHER 25
CREATE CONSTRAINT supplier_name IF NOT EXISTS
FOR (n:Supplier) REQUIRE n.name IS UNIQUE;

CYPHER 25
CREATE CONSTRAINT lot_lot_id IF NOT EXISTS
FOR (n:Lot) REQUIRE n.lot_id IS UNIQUE;